@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "Smart Home user")

System_Ext(mobileDevice, "Mobile Device", "Allows users to interact with Smart Home system")
System(smartHome, "Smart Home", "Allows users to manage heating systems, set target temperatures, turn them off and on")
System_Ext(heatingSystem, "Heating System", "Collects and transmits heating sensors telemetry data")

Rel_D(user, mobileDevice, "Using Smart Home mobile app")
Rel_D(mobileDevice, smartHome, "Viewing heating systems, turning them on and off, setting target temperatures")
Rel_R(smartHome, heatingSystem, "Sending controlling singals to heating system sensors, retrieving telemetry data")

@enduml